import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/sidebar";
import { SessionProvider } from "@/components/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Login from "@/components/Login";
import ClientProvider from "@/components/ClientProvider";
import Navbar from "@/components/Navbar";
export const metadata: Metadata = {
  title: "Chat GPT Clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session=await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className="bg-[#212121]">
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ):(
            <>
            <div className=" flex w-full">
            <div className="bg-[#171717] max-w-xs h-screen overflow-y-auto scrollbar-width-none md:min-w-[15rem] lg:min-w-[20rem]">
              <SideBar />
            </div>

            <ClientProvider />
            <div className="bg-[#212121] flex-1 w-full">
              <Navbar />
                  {children}
            </div>
          </div>
            </>
            )}
        </SessionProvider>
      </body>
    </html>
  );
}
